eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8083
spring:
    application:
        name: Match-Service
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:file:./data/Match-db
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
